name: lambda-deployment
on: push
jobs:
    create-role:
        runs-on: [ubuntu-latest,workflow_dispatch]
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: connect aws
              uses: aws-actions/configure-aws-credentials@v2
              with :
                aws-region: us-east-1
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

