name: lambda-deployment
on: [push, workflow_dispatch]
jobs:
    create-role:
        runs-on: [ubuntu-latest]
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: connect aws 
              uses: aws-actions/configure-aws-credentials@v2
              with :
                aws-region: us-east-2
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - name: aws cli execution
              run: aws s3 ls
            - name: upload artifacts
              uses: actions/upload-artifacts@v3
              with:
                name: lambda-source
                path: lambda


