name: lambda-deployment
on: push
jobs:
    create-role:
        runs-on: [ubuntu-latest,workflow_dispatch]
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: connect aws 
              uses: aws-actions/configure-aws-credentials@v2
              with :
                aws-region: us-east-1
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - name: aws cli execution
              run: aws s3 ls


